# Generated by Django 5.0.3 on 2024-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=512, unique=True)),
                ('state', models.IntegerField(default=0)),
            ],
        ),
    ]
