# Generated by Django 5.0.3 on 2024-04-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_offer_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='request_queue',
            field=models.CharField(default='[]', max_length=1024),
        ),
    ]
